pipeline {
    agent { label 'AGENT-1' }

    environment {
        PROJECT = "expense"
        COMPONENT = "backend"
        DEPLOY_ENV = "qa"
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }
 parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }


    stages {
        stage('Init') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh '''
                        cd 00-vpc
                        terraform init -reconfigure
                        terraform plan
                    '''
                }
            }
        }

    

      

        stage('Terraform Apply') {
            input {
                message "Do you want to apply the Terraform changes?"
                ok "Apply"
            }
         steps {

        withAWS(region: 'us-east-1', credentials: 'aws-creds') {
            sh '''
            cd 00-vpc
            terraform init
            terraform apply -auto-approve
           
            '''
            }
        }
    }


     stage('Trigger SG') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps{
            build job: '10-sg', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
  
                }
                
        }


    } 


    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    } 

}






