pipeline {
    agent { label 'AGENT-1' }

    environment {
        PROJECT = "expense"
        COMPONENT = "backend"
        DEPLOY_ENV = "qa"
    }

    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }

parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages {
        stage('Init') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh '''
                        cd 10-sg
                        terraform init -reconfigure
                        terraform plan
                    '''
                }
            }



           
        }

        stage('Terraform Apply') {
            input {
                message "Do you want to apply the Terraform changes?"
                ok "Apply"
            }
         steps {

        withAWS(region: 'us-east-1', credentials: 'aws-creds') {
            sh '''
            cd 10-sg
            terraform init
            terraform apply -auto-approve
           
            '''
            }
        }
    }

    
}

}
      





        

  



